suppressPackageStartupMessages({
  library("stringr")
})
EXCLUDE <- "Zelig.url"
withr::with_temp_libpaths({
  # install(here::here("Zelig"))
  zelig_data <- rlang::new_environment()
  for (d in data(package = "Zelig")[["results"]][ , 3]) {
    if (!d %in% EXCLUDE) {
      data(list = d, package = "Zelig", envir = zelig_data)
    }
  }

  dir.create(here::here("data"), showWarnings = FALSE)
  file.remove(dir(here::here("data"), pattern = "\\.rda$",
                  full.names = TRUE))
  dir.create(here::here("man"), showWarnings = FALSE)

  # Save datasets
  # the datasets in Zelig/data/* are in heterogenous formats so
  # instead save them from the loaded data
  for (dataset in ls(zelig_data)) {
    save(list = dataset, envir = zelig_data,
         file = here::here("data", str_c(dataset, ".rda")),
         compress = "bzip2")
  }

  # copy man files
  manfiles <- c(setdiff(ls(zelig_data), str_c("immi", 1:5)),
                 "immigration")
  for (dataset in manfiles) {
    src <- here::here("Zelig", "man", str_c(dataset, ".Rd"))
    text <- readLines(src)
    # need to remove autogen comments
    roxygen_lines <- str_detect(text, "^% (Generated by roxygen2| Please edit documentation in)")
    text <- text[!roxygen_lines]
    dst <- here::here("man", str_c(dataset, ".Rd"))
    cat(str_c(text, collapse = "\n"), "\n", file = dst)
  }

})